config_version = "0"

exclude_patterns = [
  "**/.github/**",
  "**/spec/**"
]

test_patterns = [
  "**/spec/**"
]

[[source]]
name = "default"
default = true

[smells]
mode = "comment"
function_parameters.threshold  = 15

[[plugin]]
name = "rubocop"
version = "1.81.0"
